"""The public innovation atlas and historical capital-allocation game."""


def render_innovation_atlas():
    return '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#171617"><meta name="description" content="Explore the companies, inventions and investment outcomes behind six decades of innovation. Play a historical investing game with $100 of starting capital.">
<title>Innovation Atlas — A History of the Future | Hetzerk Asset Management</title>
<link rel="icon" href="/assets/favicon.svg?v=wing-h-1" type="image/svg+xml"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/branding.css"><link rel="stylesheet" href="/assets/innovation-atlas.css">
<script src="/assets/innovation-game-engine.js" defer></script><script type="module" src="/assets/innovation-atlas.js"></script></head>
<body class="innovation-atlas"><a class="ia-skip" href="#atlas-main">Skip to the innovation atlas</a>
<header class="ia-header"><a class="ia-brand" href="/" aria-label="Hetzerk Asset Management home"><span class="ia-brand-mark" aria-hidden="true"></span><span>Hetzerk <small>INNOVATION ATLAS</small></span></a><nav aria-label="Atlas navigation"><button class="is-active" data-view="atlas" aria-pressed="true">Explore</button><button data-view="game" aria-pressed="false">The game</button><button data-view="scores" aria-pressed="false">Leaderboard</button><a href="/play/" class="ia-site-link">Play ↗</a><a href="/etfs/redi/" class="ia-site-link">REDI <span aria-hidden="true">↗</span></a></nav><button class="ia-motion" id="motion-toggle" aria-pressed="false" aria-label="Pause decorative animation">Pause motion <span aria-hidden="true">Ⅱ</span></button></header>
<main id="atlas-main">
<div id="atlas-view" class="ia-view">
<section class="ia-hero" aria-labelledby="atlas-title"><div class="ia-scene" id="innovation-scene" aria-hidden="true"><div class="ia-orbit-fallback"></div></div><div class="ia-hero-grid"></div><div class="ia-hero-copy"><p class="ia-eyebrow"><span class="ia-status-dot"></span> HETZERK / A HISTORY OF THE FUTURE</p><h1 id="atlas-title">The idea.<br>The company.<br><em>The return.</em></h1><p class="ia-hero-lede">From silicon to intelligence. Follow six decades of invention—and what owning a piece of it was worth.</p><div class="ia-hero-actions"><a class="ia-primary" href="#chronicle">Enter the timeline <span>↓</span></a><button class="ia-text-button" data-view="game">Begin with $100 <span>↗</span></button></div><p class="ia-hero-footnote">Historical evidence. Open questions. A future that was never obvious.</p></div><div class="ia-hero-art-label"><span>01—07</span><p>IDEAS BECOME INDUSTRIES.<br>INDUSTRIES BECOME HISTORY.</p></div><div class="ia-hero-year" id="hero-year" aria-hidden="true">1960</div><div class="ia-hero-bottom"><p>SCROLL THROUGH THE POSSIBLE</p><span class="ia-scroll-line"></span><p>1960 <span>→</span> <span data-latest-year>Today</span></p></div></section>
<section class="ia-stats" aria-label="Published archive coverage"><div><strong id="count-innovations">—</strong><span>dated product &amp; innovation records</span></div><div><strong id="count-landmarks">—</strong><span>researched landmark stories</span></div><div><strong id="count-firms">—</strong><span>company profiles</span></div><div><strong id="count-prices">—</strong><span>observed return-index prices</span></div></section>
<p class="ia-data-message ia-width" id="atlas-status" role="status">Opening the archive…</p>
<section id="chronicle" class="ia-chronicle ia-width" aria-labelledby="chronicle-heading"><div class="ia-section-heading"><div><p class="ia-eyebrow">01 / THE CHRONICLE</p><h2 id="chronicle-heading">Every breakthrough<br>has a <em>before.</em></h2></div><p>Trace the idea, the company that brought it to market, and the investor’s path. A brilliant product and a brilliant investment are different questions.</p></div>
<nav class="ia-era-rail" aria-label="Choose a decade"><button data-era="all" class="is-active" aria-pressed="true">All years</button><button data-era="1960" aria-pressed="false">1960s</button><button data-era="1970" aria-pressed="false">1970s</button><button data-era="1980" aria-pressed="false">1980s</button><button data-era="1990" aria-pressed="false">1990s</button><button data-era="2000" aria-pressed="false">2000s</button><button data-era="2010" aria-pressed="false">2010s</button><button data-era="2020" aria-pressed="false">2020s</button><span class="ia-rail-progress"></span></nav>
<div class="ia-era-intro"><div><span class="ia-era-number" id="era-number">1960—</span><h3 id="era-title">The compounding of ideas.</h3><p id="era-copy">A collection of pivotal moments, followed by the companies and products they helped make possible.</p></div><span class="ia-era-symbol" aria-hidden="true">✳</span></div>
<div class="ia-filters"><label class="ia-search"><span class="ia-sr-only">Search innovations and companies</span><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></svg><input id="atlas-search" type="search" placeholder="An idea, a company, a turning point…" autocomplete="off"></label><label><span class="ia-sr-only">Company</span><select id="atlas-company"><option value="all">Every company</option></select></label><label><span class="ia-sr-only">Collection</span><select id="atlas-collection"><option value="landmarks">Landmark stories</option><option value="all">Complete archive</option><option value="catalog">Product &amp; software records</option></select></label></div>
<div class="ia-results-heading"><p id="result-count" aria-live="polite">Preparing the timeline</p><span>THE RECORD / CHRONOLOGICAL</span></div><div id="innovation-cards" class="ia-card-grid" aria-live="polite"></div><button id="load-more" class="ia-load-more" hidden>Continue through the archive <span>↓</span></button><p id="archive-empty" class="ia-empty" hidden>No records match this view. Try another company, decade or collection.</p>
</section>
<section class="ia-game-invitation ia-width"><div class="ia-invitation-art" aria-hidden="true"><span>$100</span><i></i><i></i><i></i></div><div><p class="ia-eyebrow">02 / CONVICTION, TESTED</p><h2>It looked different<br><em>before it happened.</em></h2><p>Meet the opportunity with the information available then. Commit part of your capital, hold back, or sell an earlier position. Watch the years change what you own.</p><button class="ia-primary" data-view="game">Enter the investing game <span>↗</span></button></div></section>
</div>
<div id="game-view" class="ia-view ia-width" hidden>
<section id="game-intro" class="ia-game-intro"><div><p class="ia-eyebrow">THE HETZERK INVESTING GAME</p><h1>One hundred dollars.<br>Six decades.<br><em>Your conviction.</em></h1><p class="ia-game-intro-copy">The next great idea is sitting in front of you. So are its costs, uncertainties and competitors. How much of your capital would you commit?</p><div class="ia-hero-actions"><button id="game-start" class="ia-primary" disabled>Begin the journey <span>→</span></button><button id="game-resume" class="ia-text-button" hidden>Resume your journey ↗</button></div><p id="saved-status" class="ia-small" role="status"></p></div><div class="ia-start-capital"><span>YOUR STARTING CAPITAL</span><strong><small>$</small>100</strong><p>No borrowing. No shorting.<br>Cash earns 0%. Dividends stay invested.</p><div class="ia-capital-rings" aria-hidden="true"></div></div><div class="ia-game-rules"><article><span>01</span><h3>Read the moment.</h3><p>Opportunity, competition, and dated financial evidence. Missing historical ratios remain missing.</p></article><article><span>02</span><h3>Place your conviction.</h3><p>Invest any part of available cash. Sell an existing position to make room. Passing is a decision, too.</p></article><article><span>03</span><h3>Live with the result.</h3><p>Move through the published history until your capital reaches zero or the latest observation date.</p></article></div><p class="ia-game-qualification">A curated historical learning game with hindsight-selected companies, not an unbiased backtest or a prediction. Familiar survivors are overrepresented; missing delisted firms limit what the results can teach. All game money is fictional.</p></section>
<section id="game-active" hidden aria-labelledby="game-heading"><div class="ia-game-top"><div><p class="ia-eyebrow">YOUR JOURNEY <span id="game-counter"></span></p><h1 id="game-heading">The moment before.</h1></div><div class="ia-game-date"><span id="game-year">1962</span><small id="game-date-label"></small></div><button id="game-restart" class="ia-text-button">Start over ↺</button></div><div class="ia-game-progress"><span id="game-progress-fill"></span></div><div class="ia-portfolio-bar"><div><span>Portfolio value</span><strong id="portfolio-value">$100.00</strong></div><div><span>Available cash</span><strong id="portfolio-cash">$100.00</strong></div><div><span>Since the beginning</span><strong id="portfolio-change">0.00%</strong></div><div><span id="benchmark-title">Market reference</span><strong id="portfolio-benchmark">—</strong></div></div>
<div class="ia-game-layout"><article class="ia-decision-card"><div class="ia-decision-top"><p class="ia-eyebrow" id="decision-company"></p><span class="ia-chip" id="decision-ticker"></span></div><div class="ia-decision-art" id="decision-art" aria-hidden="true"></div><h2 id="decision-title"></h2><p class="ia-decision-date" id="decision-known-at"></p><div class="ia-decision-story"><h3>The market opportunity</h3><p id="decision-opportunity"></p><h3>The investment being made</h3><p id="decision-investment"></p><h3>What could go wrong</h3><p id="decision-risk"></p></div><dl class="ia-financial-grid" id="decision-financials"></dl><p class="ia-small" id="decision-financial-note"></p><details class="ia-decision-sources"><summary>Historical sources and dated filings</summary><ul id="decision-sources"></ul></details></article>
<aside class="ia-allocation-panel"><p class="ia-eyebrow">MAKE THE CALL</p><h2>What is your<br><em>conviction worth?</em></h2><label for="allocation-amount" class="ia-amount-label">Your investment <span id="allocation-percent">0% of available cash</span></label><div class="ia-money-input"><span>$</span><input id="allocation-amount" type="number" min="0" step="0.01" value="0" inputmode="decimal" aria-describedby="allocation-help"></div><input id="allocation-slider" type="range" min="0" max="100" value="0" step="1" aria-label="Percentage of available cash to invest"><div class="ia-allocation-presets"><button data-allocation="0">0%</button><button data-allocation="25">25%</button><button data-allocation="50">50%</button><button data-allocation="100">All in</button></div><p id="allocation-help" class="ia-small">Fractional positions. No leverage.</p><button id="game-invest" class="ia-primary">Invest &amp; advance <span>→</span></button><button id="game-pass" class="ia-secondary">Keep my cash &amp; advance</button><p id="game-error" class="ia-game-error" role="alert" hidden></p><div class="ia-holdings-heading"><h3>What you own</h3><span id="holdings-count">0 positions</span></div><div id="game-holdings"></div><p id="sale-note" class="ia-small" role="status"></p></aside></div>
<section class="ia-equity-panel"><div class="ia-chart-heading"><div><p class="ia-eyebrow">THE PATH OF YOUR CAPITAL</p><h2>Your decisions, compounded.</h2></div><p id="game-chart-note">Starting with $100</p></div><div id="game-equity-chart" class="ia-return-chart"></div><p class="ia-small">Values at decision dates. Prices between observations can move further. The market reference begins when its own history becomes available; cash earns 0% before that date.</p></section><details class="ia-trades"><summary>Your investment journal <span>↓</span></summary><div id="game-trades"></div></details><div id="game-warnings" class="ia-small"></div></section>
<section id="game-finish" class="ia-game-finish" hidden><p class="ia-eyebrow">THE JOURNEY, RECORDED</p><h1 id="finish-title">Time has<br><em>had its say.</em></h1><p class="ia-finish-value" id="finish-value"></p><p id="finish-description"></p><div id="finish-chart" class="ia-return-chart"></div><div class="ia-finish-stats" id="finish-stats"></div><form id="score-form"><label for="player-name">Name your place in the record <span>Visible if you publish a score.</span></label><div><input id="player-name" maxlength="20" placeholder="Your chosen name" autocomplete="nickname" required><button class="ia-primary" type="submit">Save this result <span>↗</span></button></div><p id="score-status" role="status" class="ia-small"></p></form><div class="ia-hero-actions"><button class="ia-secondary" id="game-again">Begin again ↺</button><button class="ia-text-button" data-view="scores">View the leaderboard ↗</button><button class="ia-text-button" id="download-replay">Download your decisions ↓</button></div><div id="finish-outcomes" class="ia-outcomes"></div></section>
</div>
<section id="scores-view" class="ia-view ia-width ia-scores-view" hidden aria-labelledby="scoreboard-title"><p class="ia-eyebrow">03 / THE RECORD OF CONVICTION</p><h1 id="scoreboard-title">Some saw possibility.<br><em>Some stayed in cash.</em></h1><p class="ia-scores-lede">Every score begins with the same $100. Every result keeps the decisions that produced it.</p><div class="ia-score-tabs" role="group" aria-label="Leaderboard scope"><button data-score-scope="local" class="is-active" aria-pressed="true">On this device</button><button data-score-scope="global" aria-pressed="false">Across players</button></div><p id="leaderboard-status" role="status" class="ia-small"></p><div class="ia-score-table-wrap"><table class="ia-score-table"><thead><tr><th scope="col">Rank</th><th scope="col">Investor</th><th scope="col">Final capital</th><th scope="col">Return</th><th scope="col">Decisions</th></tr></thead><tbody id="leaderboard-body"></tbody></table></div><p class="ia-small">Scores are grouped by the same data edition and rules. Replaying the decisions checks the arithmetic; it cannot establish that a player did not know the future. No sample players or invented rankings are shown.</p><button class="ia-primary" data-view="game">Make your own record <span>→</span></button></section>
<section id="atlas-method" class="ia-method ia-width"><details><summary><span><span class="ia-eyebrow">THE RESEARCH NOTES</span><strong>What the record can—and cannot—tell us.</strong></span><span>+</span></summary><div class="ia-method-grid"><article><h3>Innovation is an ecosystem.</h3><p>Researched landmarks distinguish invention from development and commercialization. The wider archive contains dated product and software records attributed to a manufacturer or developer; these are not thousands of independently audited inventions. Contributions often span public labs, universities, private firms and individual inventors.</p><h3>Returns belong to the company.</h3><p>A stock return reflects all of a firm’s activities, valuation changes and market conditions. It does not identify the causal return on one innovation. “Lifecycle” views show elapsed investment windows following a milestone, not a claim about when a technology matured.</p></article><article><h3>Follow the observed history.</h3><p>Historical adjusted closes from Yahoo Finance are used as provider-adjusted total-return proxies, including its split and dividend adjustments. We do not count dividends or splits twice. Spin-offs, acquisitions, delistings, provider corrections and incomplete histories can prevent a complete shareholder-wealth reconstruction. Available dates are always shown; history is not manufactured back to 1960.</p><h3>The game has boundaries.</h3><p>Trades use observed prices on the decision date after the event. Partial-year dates are treated conservatively. Cash earns no interest, and there are no fees, taxes, borrowing or short positions. Fractional return-index units represent reinvestment; they are not actual historical share quantities. The SPY market reference holds cash before its first available 1993 observation, then follows its adjusted returns. It is not a continuous market index back to 1960. Famous surviving firms are overrepresented. Historical financials are shown only with dated evidence and reporting availability.</p></article><article><h3>Sources &amp; coverage</h3><div id="coverage-notes"></div><ul><li><a href="https://www.wikidata.org/wiki/Wikidata:Main_Page" target="_blank" rel="noopener noreferrer">Wikidata structured product records (CC0) ↗</a></li><li><a href="https://www.sec.gov/edgar/search/" target="_blank" rel="noopener noreferrer">SEC filings and company facts ↗</a></li><li><a href="https://finance.yahoo.com/" target="_blank" rel="noopener noreferrer">Yahoo Finance historical market data ↗</a></li></ul><a href="/innovation/data.json" download>Download the dated archive ↓</a><h3>Your game stays yours.</h3><p>Progress and device scores are saved in this browser. A public score is sent only when you choose to publish it; it includes your chosen name and decision history. Clearing browser data removes local saves.</p></article></div></details></section>
</main><footer class="ia-footer ia-width"><div><strong>Hetzerk Asset Management</strong><p>Investing in Innovation, REDI for tomorrow.</p></div><nav aria-label="Footer navigation"><a href="/etfs/redi/">The ETF</a><a href="/research/">Research</a><a href="/privacy/">Privacy</a><a href="/disclosures/">Disclosures</a></nav><p class="ia-small">An educational historical experience. Not investment advice. Investing involves risk, including loss of principal. Past performance does not predict future results.</p></footer>
<dialog id="innovation-detail" class="ia-detail-dialog" aria-labelledby="detail-title"><div class="ia-detail-toolbar"><span class="ia-eyebrow">FROM THE ARCHIVE</span><button id="detail-close" aria-label="Close innovation details">×</button></div><div id="detail-content"></div></dialog>
<dialog id="restart-dialog" class="ia-confirm-dialog" aria-labelledby="restart-title"><p class="ia-eyebrow">A FRESH START</p><h2 id="restart-title">Begin again?</h2><p>Your current journey will be replaced. Completed leaderboard entries remain saved.</p><div><button id="restart-confirm" class="ia-primary">Start with $100</button><button id="restart-cancel" class="ia-secondary">Keep my journey</button></div></dialog>
<div id="ia-live" class="ia-sr-only" role="status" aria-live="polite"></div><noscript><p class="ia-width">This interactive archive and game require JavaScript. The <a href="/innovation/data.json">sourced dataset remains available to download</a>.</p></noscript></body></html>'''
