"""The compact, game-first Hetzerk Innovation Run web app."""


def render_innovation_play():
    return '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#181617"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-title" content="REDI Play"><meta name="description" content="Twelve investment decisions. One hundred fictional dollars. Play through the history of innovation in Hetzerk Innovation Run."><title>REDI Play — Innovation Run | Hetzerk Asset Management</title><link rel="icon" href="/assets/favicon.svg?v=wing-h-1" type="image/svg+xml"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/branding.css"><link rel="stylesheet" href="/assets/innovation-play.css"><script src="/assets/innovation-game-engine.js" defer></script><script src="/assets/innovation-arcade-engine.js" defer></script><script src="/assets/innovation-play.js" defer></script></head>
<body class="innovation-play"><a class="play-skip" href="#main">Skip to game</a>
<header class="play-header"><a class="play-brand" href="/" aria-label="Hetzerk Asset Management home"><span class="play-mark" aria-hidden="true"></span><span>Hetzerk<small>REDI PLAY / INNOVATION RUN</small></span></a><div class="play-header-right"><a class="play-atlas-link" href="/innovation/">The Atlas <span aria-hidden="true">↗</span></a><button type="button" id="play-motion" class="play-icon-button" aria-pressed="false" aria-label="Pause decorative motion"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M9 6v12M15 6v12"/></svg></button><button type="button" class="play-icon-button" data-open-scores aria-label="Open local leaderboard"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M8 4h8v5a4 4 0 0 1-8 0V4ZM8 6H4v2a4 4 0 0 0 5 4m7-6h4v2a4 4 0 0 1-5 4M12 13v6m-4 1h8"/></svg></button></div></header>
<main id="main" class="play-main">
<div class="play-topline"><div class="play-mode-switch" role="group" aria-label="Game mode"><button type="button" data-mode="classic" aria-pressed="true">Classic<span>THE LONG VIEW</span></button><button type="button" data-mode="daily" aria-pressed="false">Daily<span>A NEW FLIGHT</span></button></div><p id="play-edition">Opening the archive…</p></div>
<p id="play-error" class="play-error" role="alert" hidden></p>
<section class="play-cabinet" aria-label="Innovation Run game">
<div class="play-sky" id="play-sky"><div class="play-grain" aria-hidden="true"></div><div class="play-era-year" id="play-era-year" aria-hidden="true">1962</div><div class="play-orbit play-orbit-one" aria-hidden="true"></div><div class="play-orbit play-orbit-two" aria-hidden="true"></div>
<div class="play-hud"><div><span>YOUR CAPITAL</span><strong id="play-capital">$100<span>.00</span></strong></div><div class="play-round-hud"><span id="play-round-label">THE BEGINNING</span><strong id="play-round">00 <small>/ 12</small></strong></div></div>
<svg class="play-landscape" viewBox="0 0 1000 500" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="play-ground-gradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#8b4b43" stop-opacity=".4"/><stop offset="1" stop-color="#211a1c" stop-opacity="0"/></linearGradient><linearGradient id="play-trail-gradient"><stop stop-color="#bc6b63" stop-opacity="0"/><stop offset="1" stop-color="#efbd7e"/></linearGradient><pattern id="play-grid-pattern" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M50 0H0V50" fill="none" stroke="#deb99a" stroke-opacity=".08"/></pattern></defs><rect width="1000" height="500" fill="url(#play-grid-pattern)"/><g class="play-distant-city"><path d="M-200 460V359h35v44h34V307h27v91h46V345h42v59h43V275h27v34h20v113h42V330h50v65h27V240h17v-23h16v23h17v176h39V359h43v47h44V288h31v-44h8v44h28v124h30V340h47v51h40V310h26v-21h8v21h28v103h35V265h28v-25h8v25h26v147h25V350h39v63h39V312h27v-40h9v40h27v104h36V332h30v76h47V262h35v143h60v-97h33v91h30v-42h53v103Z" fill="#b07465" opacity=".11"/></g><path d="M0 467C190 366 322 462 493 406S823 315 1000 352V500H0Z" fill="url(#play-ground-gradient)"/><path d="M0 468C220 385 430 467 600 399S875 335 1000 351" fill="none" stroke="#bc7d65" stroke-opacity=".26"/><path id="play-flight-path" d="M80 350C130 340 162 329 205 328" fill="none" stroke="url(#play-trail-gradient)" stroke-width="3" stroke-linecap="round"/><g id="play-path-dots"></g></svg>
<div id="play-gates" class="play-gates" aria-hidden="true"></div><div id="play-flyer" class="play-flyer" aria-hidden="true"><span class="play-flyer-halo"></span><span class="play-flyer-mark"></span><span class="play-flyer-trail"></span></div><div class="play-scene-bottom"><span id="play-era-name">THE NEXT IDEA IS AHEAD</span><span id="play-scene-date">NO TIMER. YOUR CALL.</span></div>
<div class="play-welcome" id="play-welcome"><p class="play-eyebrow">A LITTLE CONVICTION GOES A LONG WAY</p><h1>Time flies.<br> <em>Make the call.</em></h1><p>Twelve decisions. One hundred dollars.<br>A lifetime of <em>what if.</em></p><button type="button" id="play-start" class="play-primary" disabled>Loading history… <span aria-hidden="true">→</span></button><button type="button" id="play-resume" class="play-resume" hidden>Resume your run <span aria-hidden="true">↗</span></button><span class="play-start-note">FICTIONAL CAPITAL. REAL HISTORICAL PRICES.</span></div>
<div class="play-reveal" id="play-reveal" hidden aria-labelledby="play-reveal-title"><p class="play-eyebrow" id="play-reveal-date"></p><h2 id="play-reveal-title">The years moved.</h2><strong id="play-reveal-capital"></strong><p id="play-reveal-change"></p><p id="play-reveal-allocation"></p><button type="button" id="play-continue" class="play-primary">Next idea <span aria-hidden="true">→</span></button></div>
</div>
<div class="play-console">
<div id="play-idle" class="play-idle"><div class="play-idle-icon" aria-hidden="true">✳</div><p class="play-eyebrow">THE RULE IS SIMPLE</p><h2>Spot the idea.<br> <em>Place your conviction.</em></h2><p>Put 0%, 25%, 50% or all of your capital behind each company. Fly to the next moment in history. See what your decisions were worth.</p><div class="play-idle-facts"><span><strong>12</strong>DECISIONS</span><span><strong>$100</strong>TO BEGIN</span><span><strong>∞</strong>WAYS TO LEARN</span></div><p class="play-idle-note">Every round rebalances. No borrowing. No real money. Take as long as you like.</p></div>
<article id="play-decision" class="play-decision" hidden aria-labelledby="play-decision-title"><div class="play-card-top"><p class="play-eyebrow" id="play-company"></p><span id="play-ticker" class="play-ticker"></span></div><h2 id="play-decision-title"></h2><p id="play-decision-date" class="play-decision-date"></p><p id="play-opportunity" class="play-opportunity"></p><dl class="play-facts"><div><dt>PRICE / FILED EPS</dt><dd id="play-valuation">—</dd></div><div><dt>ANNUAL R&amp;D</dt><dd id="play-rd">—</dd></div></dl><button type="button" id="play-more" class="play-more">Read the decision brief <span aria-hidden="true">↗</span></button><div class="play-allocation-heading"><span>HOW MUCH OF YOUR CAPITAL?</span><strong id="play-available">$100.00</strong></div><div class="play-choices" role="group" aria-label="Allocate capital to this company"><button type="button" data-fraction="0"><strong>Pass</strong><small>STAY IN CASH</small></button><button type="button" data-fraction="0.25"><strong>25<small>%</small></strong><small>TEST THE IDEA</small></button><button type="button" data-fraction="0.5"><strong>50<small>%</small></strong><small>LEAN IN</small></button><button type="button" data-fraction="1"><strong>All in</strong><small>FULL CONVICTION</small></button></div><p class="play-choice-note" id="play-choice-note">One company per round. The rest stays in cash.</p></article>
<section id="play-finish" class="play-finish" hidden aria-labelledby="play-finish-title"><p class="play-eyebrow">THE FLIGHT, RECORDED</p><h2 id="play-finish-title">You made<br> <em>your own history.</em></h2><p id="play-finish-summary"></p><dl class="play-finish-stats"><div><dt>FINAL CAPITAL</dt><dd id="play-final-value"></dd></div><div><dt>CHANGE</dt><dd id="play-final-change"></dd></div></dl><form id="play-score-form"><label for="play-name">Name this run <span>Saved on this device only.</span></label><div><input id="play-name" value="You" maxlength="20" autocomplete="nickname" required><button type="submit">Save score <span aria-hidden="true">↗</span></button></div><p id="play-score-status" role="status"></p></form><button type="button" id="play-again" class="play-primary">One more flight <span aria-hidden="true">↺</span></button><button type="button" data-open-scores class="play-more">Your local leaderboard <span aria-hidden="true">↗</span></button></section>
</div>
</section>
<div class="play-bottom-bar"><div id="play-progress" class="play-progress" aria-label="Game progress"></div><button type="button" id="play-restart" hidden>New run <span aria-hidden="true">↺</span></button><button type="button" id="play-rules-open">Rules &amp; sources <span aria-hidden="true">↗</span></div>
<p class="play-qualification">Fictional capital. Hindsight-selected companies. An investing game, not a forecast or an unbiased backtest.</p><p id="play-live" class="play-sr-only" role="status" aria-live="polite"></p><noscript><p class="play-error">This game needs JavaScript. You can still explore the <a href="/innovation/">Innovation Atlas</a>.</p></noscript>
</main>
<dialog id="play-brief-dialog" class="play-dialog" aria-labelledby="play-brief-heading"><div class="play-dialog-top"><p class="play-eyebrow">THE MOMENT BEFORE</p><button type="button" data-close-dialog aria-label="Close decision brief">×</button></div><h2 id="play-brief-heading"></h2><p id="play-brief-date" class="play-dialog-subtitle"></p><div id="play-brief-copy"></div><div id="play-brief-sources"></div></dialog>
<dialog id="play-rules-dialog" class="play-dialog" aria-labelledby="play-rules-heading"><div class="play-dialog-top"><p class="play-eyebrow">THE SMALL PRINT, IN PLAIN SIGHT</p><button type="button" data-close-dialog aria-label="Close game rules">×</button></div><h2 id="play-rules-heading">A flight through<br><em>what actually happened.</em></h2><ol class="play-rules-list"><li><strong>Begin with $100 of fictional capital.</strong> Each round sells the previous position, then allocates your chosen fraction to one company. The remainder holds cash at 0% interest. No borrowing, shorting, fees or taxes.</li><li><strong>Make twelve chronological decisions.</strong> Classic keeps the same route within a data edition. Daily uses the UTC calendar date to choose a route. There is no timer. You can replay and learn.</li><li><strong>Own the company, not the invention.</strong> Results follow the company’s provider-adjusted price history through the next decision date. They do not measure the return caused by a particular invention. Distributions and splits are already reflected; they are not added twice.</li><li><strong>History has gaps.</strong> This is a curated, hindsight-selected exercise. Famous survivors are overrepresented, delisted firms and corporate actions may be incomplete, and some inventions predate investable price history. Financial ratios remain unavailable without dated evidence. Decision briefs are editorial reconstructions.</li><li><strong>Your leaderboard stays on your device.</strong> Runs are compared only within the same data edition, game mode and daily date. Saving replays checks the arithmetic, not whether a player knew the future. This device keeps the best 20 runs per current edition; older editions have limited retention. Clearing browser storage removes saved runs.</li></ol><div class="play-source-links"><a href="/play/support.html">REDI Play support ↗</a><a href="/innovation/">Explore the sourced Innovation Atlas ↗</a><a id="play-data-link" href="/innovation/data.json" download>Download the historical dataset ↓</a><a href="https://finance.yahoo.com/" target="_blank" rel="noopener noreferrer">Yahoo Finance historical market data ↗</a></div></dialog>
<dialog id="play-scores-dialog" class="play-dialog play-scores-dialog" aria-labelledby="play-scores-heading"><div class="play-dialog-top"><p class="play-eyebrow">ON THIS DEVICE</p><button type="button" data-close-dialog aria-label="Close leaderboard">×</button></div><h2 id="play-scores-heading">Your record<br><em>of conviction.</em></h2><p id="play-scores-edition" class="play-dialog-subtitle"></p><ol id="play-scores-list" class="play-scores-list"></ol><p class="play-dialog-footnote">No public rankings. Same route, same data edition. Replays verify the arithmetic; they cannot remove hindsight.</p></dialog>
<dialog id="play-restart-dialog" class="play-dialog play-confirm-dialog" aria-labelledby="play-restart-heading"><div class="play-dialog-top"><p class="play-eyebrow">A FRESH FLIGHT</p><button type="button" data-close-dialog aria-label="Keep the current run">×</button></div><h2 id="play-restart-heading">Start again?</h2><p>This replaces the unfinished run in this mode. Completed scores stay on this device.</p><div class="play-confirm-actions"><button type="button" id="play-restart-confirm" class="play-primary">Start a new run ↺</button><button type="button" data-close-dialog class="play-more">Keep playing</button></div></dialog>
</body></html>'''
