"""A shared, explicitly labeled research chart for Compare and the REDI page."""
from html import escape


def render_strategy_research(prefix='research'):
    prefix = escape(prefix, quote=True)
    return f'''<section class="sr-panel" data-strategy-research aria-labelledby="{prefix}-title">
      <div class="sr-heading"><div><p class="sr-eyebrow">The strategy / Historical backtests</p><h2 class="sr-title" id="{prefix}-title">Log returns.<br><em>A longer perspective.</em></h2><p class="sr-intro">Follow Innovation Leader, Laggard and the Market Backtest through the monthly research record.</p></div><div class="sr-source-badge"><span>MONTHLY OBSERVATIONS</span><strong data-sr-coverage>2003—2026</strong><small>Transcribed from the source tables</small></div></div>
      <div class="sr-disclosure"><span class="sr-disclosure-mark" aria-hidden="true">R</span><p>Hypothetical strategy research, not REDI’s NAV, Market Price or actual ETF returns. Source values are rounded to two decimals. Fee and trading-cost treatment is unverified.</p></div>
      <div class="sr-selection"><fieldset><legend>Research cohorts <span>Innovation Leader + up to 3 comparisons</span></legend><div class="sr-chips" data-sr-research-chips><span class="sr-reference-chip"><i aria-hidden="true"></i>Innovation Leader<small>REFERENCE</small></span><span class="sr-loading">Loading the research record…</span></div></fieldset><fieldset class="sr-etf-fieldset"><legend>Add an ETF <span>Distributions reinvested · shared month-ends</span></legend><div class="sr-chips sr-etf-chips" data-sr-etf-chips></div></fieldset></div>
      <div class="sr-chart-top"><div><p data-sr-status role="status">Opening the monthly observations…</p><p class="sr-range" data-sr-range>Each series starts at 100 on the first shared month-end.</p></div><div class="sr-chart-controls"><div class="sr-periods" role="group" aria-label="Research comparison period"><button type="button" data-sr-period="1Y" aria-pressed="false">1Y</button><button type="button" data-sr-period="5Y" aria-pressed="false">5Y</button><button type="button" data-sr-period="10Y" aria-pressed="false">10Y</button><button type="button" data-sr-period="ALL" aria-pressed="true">All</button></div><div class="sr-scales" role="group" aria-label="Chart scale"><button type="button" data-sr-scale="log" aria-pressed="true">Log</button><button type="button" data-sr-scale="linear" aria-pressed="false">Linear</button></div></div></div>
      <p class="sr-warning" data-sr-warning role="status" hidden></p>
      <div class="sr-chart-wrap"><svg class="sr-chart" data-sr-chart viewBox="0 0 960 360" role="img" aria-label="Strategy research chart. Data is loading."></svg><p class="sr-chart-empty" data-sr-empty hidden></p></div>
      <div class="sr-chart-bottom"><ul class="sr-legend" data-sr-legend aria-label="Research chart series"></ul><span data-sr-unit>Growth of 100 · logarithmic scale</span></div>
      <div class="sr-inspector"><label for="{prefix}-cursor">Inspect a month <span>Drag or use the arrow keys</span></label><input id="{prefix}-cursor" data-sr-cursor type="range" min="0" max="0" value="0" disabled aria-describedby="{prefix}-readout"><p id="{prefix}-readout" data-sr-readout role="status" aria-live="polite">Select a month to inspect each series.</p></div>
      <div class="sr-results"><div class="sr-results-heading"><h3>Over the shared period.</h3><span>MONTH-END OBSERVATIONS</span></div><p class="sr-table-hint" aria-hidden="true">Swipe for all metrics <span>→</span></p><div class="sr-table-scroll" tabindex="0" role="region" aria-label="Research return comparison; scroll for all columns"><table class="sr-table"><caption class="sr-visually-hidden">Returns and month-end drawdowns for the selected research comparison</caption><thead><tr><th scope="col">Series</th><th scope="col">Cumulative change</th><th scope="col">Annualized growth</th><th scope="col">Month-end drawdown</th></tr></thead><tbody data-sr-table><tr><td colspan="4">Loading monthly observations…</td></tr></tbody></table></div><p class="sr-risk-note">Drawdown uses month-end values and can understate losses within a month. Annualized growth is unavailable for periods shorter than one year.</p></div>
      <details class="sr-method"><summary><span>Read the record behind the chart.</span><span aria-hidden="true">+</span></summary><div class="sr-method-grid"><div><h3>What “Log returns” means here</h3><p>The default view plots growth of 100 on a logarithmic scale. It is not a chart of individual monthly log returns. Linear changes only the chart scale; it does not change observations or calculated returns.</p><h3>Observed monthly values</h3><p>The source tables supply monthly cumulative strategy levels, rounded to two decimals. These are transcribed observations, not values estimated from the picture. Each line is rebased to 100 at the first shared month-end. No missing months are invented.</p><h3>The Market Backtest</h3><p>Market Backtest is the source research comparison. Its index identity is unverified; it is not identified as SPY, the S&amp;P 500 or the Morningstar US Market Index.</p><h3>Research has limitations</h3><p>These are historical backtests, not live fund performance. Fee, trading-cost and distribution treatment for the research have not been independently verified. The fund’s 0.45% expense ratio is not applied to the backtests. Past performance does not guarantee future results.</p></div><div><h3>Adding market history</h3><p>ETF comparisons use Yahoo market-price observations with distributions reinvested at the ex-date close, sampled at shared month-ends. ETF inception and available history can shorten the period. The backtest’s unverified cost and distribution conventions can differ from the ETF calculation.</p><h3>Source record</h3><p data-sr-source>Source details will appear with the research dataset.</p><ul class="sr-method-notes" data-sr-method-notes></ul><div class="sr-source-links"><a data-sr-research-link href="/compare/research.json" download>Download monthly research data <span aria-hidden="true">↓</span></a><a data-sr-market-link href="/compare/data.json" download>Download ETF observations <span aria-hidden="true">↓</span></a><a href="/research/the-measure-of-fire.html">Read the investment research <span aria-hidden="true">↗</span></a></div></div></div></details>
      <noscript><p class="sr-warning">Enable JavaScript to explore these observations. Monthly research data can be downloaded above.</p></noscript>
    </section>'''


def attach_strategy_research_assets(page):
    for filename, tag in (('strategy-research.css', 'link'),
                          ('comparison-math.js', 'script'),
                          ('strategy-research-math.js', 'script'),
                          ('strategy-research.js', 'script')):
        attribute = 'href' if tag == 'link' else 'src'
        url = '/assets/' + filename
        if page.select_one(f'{tag}[{attribute}="{url}"]'):
            continue
        attrs = {attribute: url}
        attrs.update({'rel': 'stylesheet'} if tag == 'link' else {'defer': ''})
        page.head.append(page.new_tag(tag, attrs=attrs))
